platform :ios, '8.0'
pod 'LBBlurredImage'
pod 'ASIHTTPRequest'
pod 'EGOTableViewPullRefresh'
pod 'MBProgressHUD'
pod 'SocketRocket'
#pod 'AMap3DMap' #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
#pod 'AMapSearch' #搜索服务SDK
pod 'SDWebImage', '~>3.7'
pod 'Masonry'
pod 'YYWebImage'
pod 'YYModel'
pod 'NJKWebViewProgress'
pod 'AFNetworking'
#pod 'AsyncDisplayKit'
